# Generated by Django 2.1.5 on 2019-02-13 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_choice_choice_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='small_image',
            field=models.CharField(default='', max_length=400),
        ),
    ]
