# Generated by Django 2.1.5 on 2019-02-14 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20190213_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_firstname',
            field=models.CharField(default='', max_length=50),
        ),
    ]
