# Generated by Django 2.1.5 on 2019-02-14 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_user_user_firstname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_firstname',
            new_name='fullname',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_email',
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(default='', max_length=100),
        ),
    ]
