# Generated by Django 2.1.5 on 2019-02-14 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20190213_1909'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='email',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='fullname',
            new_name='First_Name',
        ),
        migrations.AddField(
            model_name='user',
            name='Last_Name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
