# Generated by Django 2.1.5 on 2019-02-14 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_auto_20190213_1912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Last_Name',
        ),
    ]
