# Generated by Django 2.1.5 on 2019-02-14 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_remove_user_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='small_image',
        ),
    ]
